config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'

  resources :users, only: %i[new create]

  resources :questions do
    resources :answers, except: %i[show new]
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question

  MIN_BODY_LENGTH = 2
  MAX_BODY_LENGTH = 200

  validates :body, presence: true, length: { minimum: MIN_BODY_LENGTH, maximum: MAX_BODY_LENGTH }

  def formated_date
    created_at.strftime('%d.%m.%Y %H:%M')
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  MIN_TITLE_LENGTH = 2
  MAX_TITLE_LENGTH = 40
  MIN_BODY_LENGTH = 2
  MAX_BODY_LENGTH = 200

  validates :title, presence: true, length: { minimum: MIN_TITLE_LENGTH, maximum: MAX_TITLE_LENGTH }
  validates :body, presence: true, length: { minimum: MIN_BODY_LENGTH, maximum: MAX_BODY_LENGTH }

  scope :today, -> { where(created_at: Time.zone.now.at_beginning_of_day...Time.zone.now) }
  scope :past_week, -> { where(created_at: Time.zone.now.at_beginning_of_week...Time.zone.now.at_end_of_week) }

  def formated_date
    created_at.strftime('%d.%m.%Y %H:%M')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :set_question!
  before_action :set_answer!, only: %i[edit update destroy]

  def create
    @answer = @question.answers.build answer_params

    if @answer.save
      flash[:success] = 'Answer created!'
      redirect_to question_path(@question)
    else
      @answers = @question.answers.order created_ad: :desc
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy
    flash[:success] = 'Answer deleted!'
    redirect_to question_path(@question)
  end

  def edit; end

  def update
    if @answer.update answer_params
      flash[:success] = 'Answer updated!'
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  private

  def set_answer!
    @answer = @question.answers.find params[:id]
  end

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find params[:question_id]
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ErrorHandling

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end

  def user_sign_in?
    current_user.present?
  end

  helper_method :current_user, :user_sign_in?
end

app/controllers/concerns/error_handling.rb
# frozen_string_literal: true

module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    private

    def not_found
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[edit update show destroy]

  def index
    @questions = Question.order(created_at: :desc).page(params[:page]).per(7)
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params

    if @question.save
      redirect_to questions_path
      flash[:success] = 'Question created!'
    else
      render :new
    end
  end

  def update
    if @question.update question_params
      redirect_to questions_path
      flash[:success] = 'Question updated!'
    else
      render :new
    end
  end

  def show
    @answer = @question.answers.build
    @answers = @question.answers.order(created_ad: :desc).page(params[:page]).per(5)
  end

  def edit;	end

  def destroy
    @question.destroy
    redirect_to questions_path
    flash[:success] = 'Question deleted!'
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question!
    @question = Question.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
                        "#{options[:class]} #{css_class}"
                      else
                        css_class
                      end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: { current_page: }
  end

  def title(page_title = '')
    base_title = 'Blog'
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/views/answers/_answer.html.erb
<article class="mb-3 card">
  <div class="card-body">
    <section class="card-text">
      <small>
        <time datetime="<%= answer.formated_date %>">
          <%= answer.formated_date %>
        </time> 
      </small>
      <div class="mt-2 mb-3">
        <%= sanitize answer.body %>
      </div>
    </section>
    <%= link_to 'Edit', edit_question_answer_path(question, answer), class: 'btn btn-info btn-sm' %>
    <%= button_to 'Destroy', question_answer_path(question, answer), method: :delete, class: 'btn btn-danger mb-2' %>
  </div>
</article>

app/views/answers/_form.html.erb
<%= simple_form_for [@question, @answer], defaults: { input_html: { class: 'mb-3' } } do |f|%>
  <%= f.input :body, minlength: Answer::MIN_BODY_LENGTH, maxlength: Answer::MAX_BODY_LENGTH,
    placeholder: 'Body for answer' %>
  
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/answers/edit.html.erb
<% currently_at 'Answers' %>

<%= provide :page_title, 'Edit answer' %>

<h1 class="mb-4">Edit answer</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield :main_menu %>

    <main class="container mt-3">
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<% currently_at 'Home' %>
<h1>Home page</h1>
<%= Time.now.year %>
<%= current_user.inspect %>

app/views/questions/_form.html.erb
<%= simple_form_for @question, defaults: { input_html: { class: 'mb-3' } } do |f|%>
  <%= f.input :title, minlength: Question::MIN_TITLE_LENGTH, maxlength: Question::MAX_TITLE_LENGTH,
    placeholder: 'Title for question' %>

  <%= f.input :body, minlength: Question::MIN_BODY_LENGTH, maxlength: Question::MAX_BODY_LENGTH %>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/questions/_question.html.erb
<style>
  .question_buttons{
    display: flex;
    flex-direction: row;
  }
</style>

<article class="card mt-3">
  <div class="card-body">
    <h4><%= question.title %></h2>
    <section class="card-text">
      <time>
        <small><%= question.formated_date %></small>
      </time>
      <div class="my-2">
        <%= truncate strip_tags(question.body), length: 120, omission: '... (continued)' %>
      </div>
    </section>
    <div class="question_buttons">
      <%= link_to 'Show', question_path(question), class: 'btn btn-primary' %> 
      <%= link_to 'Edit', edit_question_path(question), class: 'btn btn-secondary mx-2' %>
      <%= button_to 'Destroy', question_path(question), method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</article>

app/views/questions/edit.html.erb
<% currently_at 'Questions' %>

<%= provide :page_title, 'Edit question' %>

<h1 class="mb-4">Edit question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<%= provide :page_title, 'Questions' %>
<% currently_at 'Questions' %>

<h1>Questions</h1>

<%= link_to 'Create question', new_question_path, class: 'btn btn-primary btn-lg mb-4' %>

<% unless @questions.present? %>
  <%= render 'shared/empty' %>
<% end %>

<%= paginate @questions %>
<%= render @questions %>
<%= paginate @questions %>

app/views/questions/new.html.erb
<%= provide :page_title, 'New question' %>
<% currently_at 'Questions' %>
<h1 class="mb-4">New question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<style>
  .question_buttons{
    display: flex;
    flex-direction: row;
  }
</style>

<% currently_at 'Questions' %>

<h1 class="mb-4">Question<%= @question.id %></h1>

<h4><%= @question.title %></h2>
<section class="card-text">
  <time>
    <small><%= @question.formated_date %></small>
  </time>
  <div class="my-2">
    <%= sanitize @question.body %>
  </div>
</section>
<div class="question_buttons mb-4">
  <%= link_to 'Show', question_path(@question), class: 'btn btn-primary' %> 
  <%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-secondary mx-2' %>
  <%= button_to 'Destroy', question_path(@question), method: :delete, class: 'btn btn-danger' %>
</div>

<h2 class="mb-2">Write your answer</h2>

<%= render 'answers/form' %>

<% unless @question.answers.all.size == 0 %>
  <h2 class="mb-2 mt-4">Answers</h2>
<% end %>
<%= paginate @answers %>
<%= render partial: 'answers/answer', collection: @answers, as: :answer,
 locals: {question: @question} %>
<%= paginate @answers %>

app/views/shared/_empty.html.erb
<h1 class="mt-4">No questions yet</h1>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Home', root_path, class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Questions', questions_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% if user_sign_in? %>
            <a class="nav-link text-white" href="javascript: void(0)"><%= current_user.name %></a>
          <% else %>
            <li><%= nav_tab 'Sign Up', new_user_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul> 
      </nav>  
    </div>
  </header>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user, defaults: { input_html: { class: 'mb-3' } } do |f|%>
  <%= f.input :email %>
  <%= f.input :name %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>

  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<%= provide :page_title, 'New User' %>
<% currently_at 'Sign Up' %>
<h1 class="mb-4">Registration</h1>
<%= render 'form' %>